export const data =[{
  "id": 1,
  "first_name": "Waylon",
  "last_name": "Mathison",
  "email": "wmathison0@telegraph.co.uk",
  "gender": "Bigender"
}, {
  "id": 2,
  "first_name": "Bree",
  "last_name": "De Fries",
  "email": "bdefries1@sphinn.com",
  "gender": "Female"
}, {
  "id": 3,
  "first_name": "Selma",
  "last_name": "Kneal",
  "email": "skneal2@prlog.org",
  "gender": "Female"
}, {
  "id": 4,
  "first_name": "Belva",
  "last_name": "Howard",
  "email": "bhoward3@dailymotion.com",
  "gender": "Female"
}, {
  "id": 5,
  "first_name": "Krissy",
  "last_name": "Perigo",
  "email": "kperigo4@ning.com",
  "gender": "Female"
}, {
  "id": 6,
  "first_name": "Stevy",
  "last_name": "Karolyi",
  "email": "skarolyi5@mysql.com",
  "gender": "Male"
}, {
  "id": 7,
  "first_name": "Doroteya",
  "last_name": "Carrell",
  "email": "dcarrell6@purevolume.com",
  "gender": "Female"
}, {
  "id": 8,
  "first_name": "Pooh",
  "last_name": "Pedrocchi",
  "email": "ppedrocchi7@jiathis.com",
  "gender": "Genderqueer"
}, {
  "id": 9,
  "first_name": "Jemmy",
  "last_name": "Georgot",
  "email": "jgeorgot8@noaa.gov",
  "gender": "Female"
}, {
  "id": 10,
  "first_name": "Gabrila",
  "last_name": "Jacobson",
  "email": "gjacobson9@army.mil",
  "gender": "Female"
}, {
  "id": 11,
  "first_name": "Rudd",
  "last_name": "Smitherham",
  "email": "rsmitherhama@ameblo.jp",
  "gender": "Male"
}, {
  "id": 12,
  "first_name": "Marianne",
  "last_name": "Morad",
  "email": "mmoradb@joomla.org",
  "gender": "Female"
}, {
  "id": 13,
  "first_name": "Korrie",
  "last_name": "Threlfall",
  "email": "kthrelfallc@amazon.co.jp",
  "gender": "Female"
}, {
  "id": 14,
  "first_name": "Huntlee",
  "last_name": "Pic",
  "email": "hpicd@51.la",
  "gender": "Male"
}, {
  "id": 15,
  "first_name": "Royce",
  "last_name": "de Castelain",
  "email": "rdecastelaine@smh.com.au",
  "gender": "Male"
}, {
  "id": 16,
  "first_name": "Marillin",
  "last_name": "Eginton",
  "email": "megintonf@wufoo.com",
  "gender": "Female"
}, {
  "id": 17,
  "first_name": "Oliy",
  "last_name": "Loader",
  "email": "oloaderg@gnu.org",
  "gender": "Genderfluid"
}, {
  "id": 18,
  "first_name": "Jermaine",
  "last_name": "Eykelhof",
  "email": "jeykelhofh@zimbio.com",
  "gender": "Male"
}, {
  "id": 19,
  "first_name": "Jobyna",
  "last_name": "Doxsey",
  "email": "jdoxseyi@amazonaws.com",
  "gender": "Female"
}, {
  "id": 20,
  "first_name": "Rutter",
  "last_name": "Casey",
  "email": "rcaseyj@jugem.jp",
  "gender": "Male"
}]